package com.ces.service.module.garage.entity;

import com.ces.service.common.entity.BaseEntity;
import com.ces.service.module.garage.enums.GarageType;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.Table;
import java.math.BigDecimal;
import java.time.Instant;
import java.util.UUID;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
import org.hibernate.annotations.Generated;
import org.hibernate.annotations.GenerationTime;

/**
 * A piece of equipment (Texnika) — the single source of truth every other module (Servis,
 * Motosaat, Anbar) is meant to reference rather than duplicate.
 *
 * <p>{@code code} is generated by a database trigger ({@code trg_vehicle_code}, TEX-000001) and
 * never set from Java. {@code status} is deliberately a free column, not a Java enum: the
 * Configuration screen lets an admin add or rename statuses at runtime, which a compiled enum
 * cannot express — it is validated against {@code garage_config_values} in the service layer
 * instead.
 */
@Entity
@Table(name = "vehicles", schema = "ces_service")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class Vehicle extends BaseEntity {

    /**
     * DB-generated (TEX-000001) by {@code trg_vehicle_code} — read-only from the application's
     * point of view. {@code @Generated} tells Hibernate to select this column back after insert;
     * without it, the in-memory entity keeps the null it was built with, since a trigger-assigned
     * value is invisible to Hibernate otherwise (nothing here declares it "generated" the way a
     * sequence-backed @GeneratedValue id would be).
     */
    @Generated(GenerationTime.INSERT)
    @Column(name = "code", insertable = false, updatable = false)
    private String code;

    @Column(name = "name", nullable = false)
    private String name;

    @Enumerated(EnumType.STRING)
    @Column(name = "garage_type", nullable = false)
    private GarageType garageType;

    /** {@code customers.id} when {@link #garageType} is CUSTOMER; null when COMPANY. */
    @Column(name = "owner_id")
    private UUID ownerId;

    @Column(name = "make", nullable = false)
    private String make;

    @Column(name = "model", nullable = false)
    private String model;

    @Column(name = "year")
    private Short year;

    @Column(name = "chassis_number")
    private String chassisNumber;

    @Column(name = "serial_number")
    private String serialNumber;

    @Column(name = "plate_number")
    private String plateNumber;

    @Column(name = "vehicle_type")
    private String vehicleType;

    /** Free text — see the class javadoc. */
    @Column(name = "status", nullable = false)
    private String status;

    @Column(name = "current_location")
    private String currentLocation;

    @Column(name = "notes")
    private String notes;

    @Column(name = "uses_engine_hours", nullable = false)
    @Builder.Default
    private Boolean usesEngineHours = Boolean.TRUE;

    @Column(name = "uses_km", nullable = false)
    @Builder.Default
    private Boolean usesKm = Boolean.FALSE;

    /** Fast-read cache — kept current by the Motosaat module's trigger, never written directly. */
    @Column(name = "current_engine_hours")
    private BigDecimal currentEngineHours;

    @Column(name = "last_engine_hours_at")
    private Instant lastEngineHoursAt;

    @Column(name = "current_km")
    private BigDecimal currentKm;

    @Column(name = "last_km_at")
    private Instant lastKmAt;
}
